@startuml

    namespace MTCG {
        namespace MTCG.Game {
            class GameController {
                {field} + User Player1 +get
                {field} + User Player2 +get
                {field} + GameState State +get 

                + GameController(User Creator)
                + void Join(User joiner)
            }
        }

        namespace MTCG.Cards {
            namespace MTCG.Cards.Rules {
                MTCG.Cards.Card "0...*" *-- "0...*" Rule : ruledBy >
                abstract class Rule {
                    + abstract void Apply(Card ruledCard, Card otherCard, GameController game)
                }

                Rule <|-- MonsterVsMonsterRule
                abstract class MonsterVsMonsterRule {
                    + void Apply(Card ruledCard, Card otherCard, GameController game)
                    - abstract void TypedApply(Monster ruledMonster, Monster otherMonster, GameController game)
                }

                MonsterVsMonsterRule <|-- GobinVsDragonRule
                class GobinVsDragonRule {
                    - void TypedApply(Monster ruledMonster, Monster otherMonster, GameController game)
                }
            }
            class Deck {
                {field} + Card[4] Cards +get

                + Deck(Card[] Cards)
                + Card Draw()
            }
            Deck "0...1" *-- "0...8" Card : contains >

            abstract class Card {
                {field} + ElementType EType +get
                {field} + string Name +get
                {field} + int Damage +get
                {field} + List<Rule> Rules +get
                bla

                + Card(string name, ElementType type, int damage)
            }

            Card "0...*" *-- "1" ElementType : has Type >
            enum ElementType {
                Fire
                Water
                Normal
            }

            namespace MTCG.Cards.Monsters {
                MTCG.Cards.Card <|-- Monster
                class Monster {
                    + Monster(string name, ElementType type, int damage)
                    {field} + CreatureType CType +get
                }

                Monster "0...*" *-- "1" CreatureType : has Type >
                enum CreatureType {
                    Goblin
                    Wizard
                    Kraken
                    Knight
                    Dragon
                    Orc
                }
            }

            namespace MTCG.Cards.Spells {
                MTCG.Cards.Card <|-- Spell
                class Spell {
                    + Spell(string name, ElementType type, int damage)
                }
            }
        }
    }

@enduml